### ISSUE TITLE
Problem running pgslice in docker

### ISSUE THREAD

**Issue by zewelor** [ankane/pgslice#50]
Hi

When testing pgslice in docker ( Dockerfile provided by project and recreated myself to containerize pgslice ), there is following exception:

```
/usr/local/bundle/gems/pgslice-0.6.0/lib/pgslice/helpers.rb:51:in `rescue in connection': uninitialized constant PgSlice::Helpers::URI (NameError)

    rescue URI::InvalidURIError
              ^^^^^^^^^^^^^^^^^
        from /usr/local/bundle/gems/pgslice-0.6.0/lib/pgslice/helpers.rb:27:in `connection'
        from /usr/local/bundle/gems/pgslice-0.6.0/lib/pgslice/helpers.rb:56:in `schema'
        from /usr/local/bundle/gems/pgslice-0.6.0/lib/pgslice/helpers.rb:176:in `create_table'
        from /usr/local/bundle/gems/pgslice-0.6.0/lib/pgslice/cli/prep.rb:8:in `prep'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/pgslice-0.6.0/exe/pgslice:7:in `<top (required)>'
        from /usr/local/bundle/bin/pgslice:25:in `load'
        from /usr/local/bundle/bin/pgslice:25:in `<main>'
/usr/local/bundle/gems/pgslice-0.6.0/lib/pgslice/helpers.rb:32:in `connection': uninitialized constant PgSlice::Helpers::URI (NameError)

        uri = URI.parse(url)
              ^^^
        from /usr/local/bundle/gems/pgslice-0.6.0/lib/pgslice/helpers.rb:56:in `schema'
        from /usr/local/bundle/gems/pgslice-0.6.0/lib/pgslice/helpers.rb:176:in `create_table'
        from /usr/local/bundle/gems/pgslice-0.6.0/lib/pgslice/cli/prep.rb:8:in `prep'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/pgslice-0.6.0/exe/pgslice:7:in `<top (required)>'
        from /usr/local/bundle/bin/pgslice:25:in `load'
        from /usr/local/bundle/bin/pgslice:25:in `<main>'
```

Docker test workflow:
in repo dir:
```
docker buildx build . --no-cache -t test
docker run --rm -it test prep some dummy args --url whatever
```

I believe it might be due to https://bugs.ruby-lang.org/issues/18147 . Fix seems to require "uri" explicit.

**Comment by ankane** [comment]
Thanks @zewelor, will get a new release out shortly.

**Comment by ankane** [comment]
It looks like the `pg` gem was requiring it in `lib/pg/connection.rb` before 1.5.0, which is why the error started now.
